In [4]:
import json
import re
import pandas as pd
pd.set_option('display.max_rows', None)
with open('out5.json', 'r') as f:
    result = f.read()
    
result
res = re.split(r'\n', result)

In [5]:
res_dict = dict()
for index, string in enumerate(res):
    if string == '':
        continue
    else:
        res_dict[index] = eval(string)
    
df = pd.DataFrame(res_dict).T

In [6]:
df

,reg_wasserstein,reg_var,learning_rate,datetime,num-steps,wasserstein-epoch,sinkhorn-iteration,id,train,test
0,5,0,0.001,20200410-203023,12000,1,5,251356,"{0: 0.7950000166893005, 1: 0.8980000019073486}","{0: 0.2070000022649765, 1: 0.38600000739097595}"
1,1,0,0.0001,20200410-203023,12000,1,5,662101,"{0: 0.7925000190734863, 1: 0.8933333158493042}","{0: 0.5590000152587891, 1: 0.671999990940094}"
2,4,0,0.001,20200410-203023,12000,1,5,244061,"{0: 0.8199999928474426, 1: 0.8913333415985107}","{0: 0.19099999964237213, 1: 0.27300000190734863}"
3,10,0,0.001,20200410-203023,12000,1,5,691952,"{0: 0.8116666674613953, 1: 0.9113333225250244}","{0: 0.23600000143051147, 1: 0.38499999046325684}"
4,10,0,0.0001,20200410-203023,12000,1,5,796462,"{0: 0.7858333587646484, 1: 0.8886666893959045}","{0: 0.6190000176429749, 1: 0.7310000061988831}"
5,6,0,0.001,20200410-203023,12000,1,5,971704,"{0: 0.815833330154419, 1: 0.8993333578109741}","{0: 0.19200000166893005, 1: 0.125}"
6,2,0,0.0001,20200410-203023,12000,1,5,262634,"{0: 0.7850000262260437, 1: 0.8786666393280029}","{0: 0.22599999606609344, 1: 0.414000004529953}"
7,3,0,0.001,20200410-203023,12000,1,5,957137,"{0: 0.7983333468437195, 1: 0.8973333239555359}","{0: 0.23499999940395355, 1: 0.31700000166893005}"
8,1,0,0.001,20200410-203024,12000,1,5,980591,"{0: 0.824999988079071, 1: 0.9073333144187927}","{0: 0.734000027179718, 1: 0.7450000047683716}"
9,2,0,0.001,20200410-203023,12000,1,5,795250,"{0: 0.8133333325386047, 1: 0.909333348274231}","{0: 0.21400000154972076, 1: 0.4490000009536743}"
10,3,0,0.0001,20200410-203023,12000,1,5,907300,"{0: 0.7683333158493042, 1: 0.8939999938011169}","{0: 0.746999979019165, 1: 0.8679999709129333}"
11,9,0,0.001,20200410-203023,12000,1,5,551009,"{0: 0.7916666865348816, 1: 0.9006666541099548}","{0: 0.453000009059906, 1: 0.6179999709129333}"
12,4,0,0.0001,20200410-203023,12000,1,5,329040,"{0: 0.8083333373069763, 1: 0.8913333415985107}","{0: 0.7440000176429749, 1: 0.8140000104904175}"
13,7,0,0.001,20200410-203023,12000,1,5,745006,"{0: 0.8208333253860474, 1: 0.8939999938011169}","{0: 0.2070000022649765, 1: 0.40700000524520874}"
14,8,0,0.001,20200410-203023,12000,1,5,109896,"{0: 0.8041666746139526, 1: 0.8786666393280029}","{0: 0.21699999272823334, 1: 0.23199999332427979}"
15,9,0,0.0001,20200410-203023,12000,1,5,701516,"{0: 0.8016666769981384, 1: 0.890666663646698}","{0: 0.5709999799728394, 1: 0.6710000038146973}"
16,8,0,0.0001,20200410-203023,12000,1,5,328129,"{0: 0.7816666960716248, 1: 0.8953333497047424}","{0: 0.7670000195503235, 1: 0.8759999871253967}"
17,7,0,0.0001,20200410-203023,12000,1,5,50751,"{0: 0.8149999976158142, 1: 0.8826666474342346}","{0: 0.36000001430511475, 1: 0.5759999752044678}"
18,6,0,0.0001,20200410-203023,12000,1,5,758370,"{0: 0.8075000047683716, 1: 0.8913333415985107}","{0: 0.753000020980835, 1: 0.7760000228881836}"
19,5,0,0.0001,20200410-203023,12000,1,5,501150,"{0: 0.7991666793823242, 1: 0.8980000019073486}","{0: 0.3370000123977661, 1: 0.5929999947547913}"